# Basic Server configuration
server:
  port: 8082
  servlet:
    context-path: /football-admin

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin1:passadmin1@127.0.0:27017.mongodb.net/football-admin-db
      database: football-admin-db

#OpenApi configuration
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
#  api-docs:
#    path: /api-docs